### ISSUE TITLE
Controls not visible in VS 2015

### ISSUE THREAD

**Issue by Johndirr** [protyposis/AudioAlign#1]
The controls on the main window aren't visible in the xaml editor of VisualStudio 2015. I mean controls like the MultiTrackViewer, Buttons in general (Match & Allign, Alignment Analysis...), Textbox for the time and so on. See: http://imgur.com/sejTSZK 
Do I have to alter some settings to see them or is it just not possible because of the custom controls of Audioalign?

**Comment by protyposis** [comment]
Thanks, this seems to be an issue with the most recent VS2015 update. I committed a fix, should be working now after a rebuild.

**Comment by Johndirr** [comment]
Working now. Thank you very much!
