### ISSUE TITLE
[REQ] Audio phase/polarity fix

### ISSUE THREAD

**Issue by MarcoRavich** [protyposis/AudioAlign#11]
As discussed in [this issue](https://github.com/benfmiller/audalign/issues/39) @benfmiller's [Audalign](https://github.com/benfmiller/audalign#audalign) too, it would be extremely useful to implement some kind of post-alignment fix for phase/polarity issues.

Here's an interesting video about:
[![Why Phase And Polarity Matter - Mixing Tutorial](https://img.youtube.com/vi/IrXHVWPGdeQ/maxresdefault.jpg)](https://youtu.be/IrXHVWPGdeQ "Wach @ YouTube")

Note that some commercial app (such as PluralEyes) does automatically generates fixed audio tracks when needed.

As always, if needed, we've collected some resources [here](https://github.com/forart/HyMPS/blob/main/A_Tools.md#phasing-).

Hope that inspires.

**Comment by protyposis** [comment]
> it would be extremely useful

For whom exactly would it be extremely useful?

> Note that some commercial app (such as PluralEyes) does automatically generates fixed audio tracks when needed.

Can you back this claim? Any references or links to documentation?

**Comment by MarcoRavich** [comment]
> For whom exactly would it be extremely useful?
> 
In multi-mics recordings post processing, for example.

> Can you back this claim? Any references or links to documentation?
>
PE refers to all corrections applied as "drift-corrected" (even if the true "drifting" is not always involved):
- https://community.adobe.com/t5/premiere-pro-discussions/audio-drift-occurring/m-p/8855248

Anyway we'll try to seek it in official documentation.

**Comment by protyposis** [comment]
Drift and phase are related, but not the same. Anyway, whenever recordings from multiple unsynchronized recording devices are mixed, there is going to be some degree of non-linear drift, leading to non-linear phase shifts. It is impossible for a program to know which phase shift is desired and which needs to be removed, so all a program can do is reduce drift. Even when multiple tracks are recorded by the same device or an array of clock-synced devices, it is impossible to magically know whether a phase shift is desired.

AudioAlign contains tools to reduce drift, and also tools to manually fix phase polarity. I also agree with the verdict from your linked discussion that this should rather be handled in a DAW.

**Comment by MarcoRavich** [comment]
Of course we manage phase/polarity issues with colosed tools (such as [SoundRadix's Auto-Align](https://www.soundradix.com/products/auto-align/)) in DAW but would be cool to have an open source alternative.

Thanks anyway.
