### ISSUE TITLE
Can not add audio from video files

### ISSUE THREAD

**Issue by Johndirr** [protyposis/AudioAlign#14]
When I try to add a video file (mkv, avi) to AudioAlign I get the following error: 
> Cannot open file. Object reference not set to an instance of an object.
![grafik](https://github.com/protyposis/AudioAlign/assets/15637513/11dcc04a-4298-46de-9ec3-a529531f3427)

Adding audio files works fine.
In the previous versions that I had to build myself this was working fine, so I guess it's a bug. Or is this the correct behavior of the application?

**Comment by protyposis** [comment]
Thanks for reporting. I can confirm this is a bug, and a fix is in progress.

**Comment by protyposis** [comment]
This problem should be fixed in https://github.com/protyposis/AudioAlign/releases/tag/v1.6.0. Please let me know if it works for you.

**Comment by Johndirr** [comment]
Works like a charm now. Thank you!
