### ISSUE TITLE
Track A and B mixed up in matching point window and Alignment Graph

### ISSUE THREAD

**Issue by Johndirr** [protyposis/AudioAlign#19]
After fingerprinting it can happen that the tracks are mixed up as you can see here:
![grafik](https://github.com/protyposis/AudioAlign/assets/15637513/fa537d7e-5c69-46d3-8049-9c573b2d8d6c)
This results in a wrong display of the Alignment Graph because in an offset becomes negative when switched.

**Comment by protyposis** [comment]
Thanks for reporting.

The "mixed up tracks" are actually expected, since fingerprints are matched in both directions: Track A to B, and Track B to A (duplicates are removed).

However, in the alignment graph the offsets should be normalized. I'll need some time to investigate this.

**Comment by protyposis** [comment]
If I understood your issue correctly, this should be fixed in https://github.com/protyposis/AudioAlign/releases/tag/v1.7.0.

**Comment by Johndirr** [comment]
This is indeed fixed now. Thank you very much.
