### ISSUE TITLE
Can't open the XML generated in Adobe Premiere Pro

### ISSUE THREAD

**Issue by rrrcabral** [protyposis/AudioAlign#30]
in Premiere(and other programs like Syncalia) the xml must be in "FINAL CUT PRO XMEML" format.

**Comment by protyposis** [comment]
What XML are you referring to? The "Sync XML" export is a proprietary format for a research project and not meant to be compatible with any other tools.

**Comment by rrrcabral** [comment]
So, what i have to do to export the syncronization results to the Premiere Pro?
this 'Sony Vegas' txt seems to can't be opened in Premiere too.

**Comment by protyposis** [comment]
I'm sorry, Adobe Premiere Pro is not supported.
