### ISSUE TITLE
Prebuild Binary

### ISSUE THREAD

**Issue by Johndirr** [protyposis/AudioAlign#8]
Would you consider providing a prebuild binary of AudioAlign?

**Comment by Johndirr** [comment]
Just bumping this in the hope to not having to download VS just because I need AudioAlign again :)

**Comment by CyberLykan** [comment]
Bumping. This tool looks very useful and it would be helpful to have a prebuilt binary.

**Comment by CyberLykan** [comment]
@Johndirr Do you have a binary available?

**Comment by Johndirr** [comment]
> 
> 
> @Johndirr Do you have a binary available?

Nope, I'm sorry :(

**Comment by Johndirr** [comment]
Still hoping to get prebuild binaries :)

**Comment by CyberLykan** [comment]
> Still hoping to get prebuild binaries :)

Same here. @protyposis

**Comment by MarcoRavich** [comment]
Well, we've exchanged some mails with @protyposis and seems that there's no way to obtain bins.

Anyway we believe that there are many other devs (such as @andres-fr) able to build.

Check out our collection of open source aligners:
https://github.com/forart/HyMPS/blob/main/A_Tools.md#alignmentsynch

Hope that helps !

**Comment by IchBinGROOT** [comment]
Something new here? Or could just somebody from the community compile it and post it here?

**Comment by Trainmaster9977** [comment]
I have no idea if this will work on other machines and setups and etc, but I built my version and zipped up everything. 
[audioalign.zip](https://github.com/protyposis/AudioAlign/files/12710666/audioalign.zip)

**Comment by MarcoRavich** [comment]
> I have no idea if this will work on other machines and setups and etc, but I built my version and zipped up everything. 
>
Cool, thanks !
I'll try it soon and give you a feedback here.

However, previously asked to the main [RareWares](https://www.rarewares.org/)' builder (John Edwards) for a Windows binary, but he replied:
>I've finally got around to having a look at this! There seem to be a number of issues preventing a build, not the least of which is that it was written to use ffmpeg 3.3.3 - shared libs - and it will not build against ffmpeg 6.0. There would appear to have been many code changes within ffmpeg since 3.3.3 that would require rewrites in the application code in order to compile. So, unless the original authors can be persuaded to update their code, I don't think I can help.

Can you explain (publicly) how you managed to build it ? 

Thanks in advance !

EDIT: Just downloaded and launched your bin... won't start at all on this W10 PC.

**Comment by protyposis** [comment]
Hi all, a binary is finally available 🥳 Please check https://github.com/protyposis/AudioAlign/releases
